### ISSUE TITLE
Release 1.10 and 1.11

### ISSUE THREAD

**Issue by MargretheR** [SuperOfficeDocs/superoffice-docs#670]
1.10

- [x] #673 - show number of requests done by app
- [x] Mandatory warning on app store entry fields missing values (must update screenshots but covered by #675)
- [x] Placeholder texts added for app store text boxes (must update screenshots but covered by #675)
- [x] #674 
   - Application settings like tech contact and error reporting emails
   - Moved app authorization text to app config version, give partners the right to change
- [x] Documentation Infobox gui changes - show and hide on mouseover (must update screenshots but covered by #675)
- [x] Update pages and screenshots pertaining to versions (removed duplicates in megamenu)

1.11

- [x] #675
- [x] #676 - added to show exceptions
- [x] CustId added to API usage dropdown (covered by #673)
- [x] #679

**Comment by digitaldiina** [comment]
I reverted the changes in commit 9e4efa7 because we discovered that the color change was unintended.
Re-added the screenshot of request changes (not affected by color change and shows the new items in the left menu)
